version: "3.9"
services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 2s
      timeout: 2s
      retries: 30
  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 2s
      timeout: 2s
      retries: 30
  api:
    build: .
    environment:
      HTTP_ADDR: ":8080"
      PG_URL: "postgres://postgres:postgres@pg:5432/app?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"
    depends_on:
      pg: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports: ["8080:8080"]
    command: ["/app/api", "--migrate"]
